label variable reserve "Reserve"
label variable num_bids "Number bids"
label variable num_com "Number comments"
label variable milage "Milage"
label variable private_seller "Private seller"
label variable num_highlights "Number highlights"
label variable num_equipment "Number equipment"
label variable num_modifications "Number modifications"
label variable num_known_flaws "Number known flaws"
label variable num_service_history "Number service history"
label variable num_other_items "Number other items"
label variable num_owner_history "Number owner history"
label variable num_seller_notes "Number seller notes"
label variable num_videos "Number videos"
label variable sold "Sold"
label variable year "Year"
label variable title_status "Clean title"
label variable end_bid "Ending bid"
label variable num_views "Number views"
label variable num_photos "Number photos"
label variable sentiment_score "Sentiment score"
label variable num_bidders "Number bidders"